[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
stake_program = "DMZkcTtqUCv3FmDoDhhHdnyDxFuLJzidZPSgxzS8MNG9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/sid/Desktop/Siddhant/Metacrafters/Solana/solana-intermediate/module3/finalProject/keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
